### ISSUE TITLE
Hidden games break SteamUser and SteamApp

### ISSUE THREAD

**Issue by lyux94** [smiley/steamapi#23]
In Recent times i somehow randomly get this error when creating instances in a loop, i tried deleting each instance in the end of the loop, which kinda reduced the problem to a decent to non existing level but didn't fix it.

Any Idea what causes the problem?

      games = test.me.recently_played
      File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\decorators.py", line 71, in __get__
      value = self.fget(inst)
      File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\user.py", line 372, in recently_played
      return self._convert_games_list(response.games, self._id)
      File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\user.py", line 149, in _ convert_games_list
      game_obj = SteamApp(game.appid, game.name, associated_userid)
      File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\core.py", line 506, in __ getattribute__attr=item))
      AttributeError: 'APIResponse' has no attribute 'name'

**Comment by smiley** [comment]
What's your steam ID/URL? I'll try and reproduce it and look at what the API's giving me. Maybe it's returning partial responses for some reason.

**Comment by lyux94** [comment]
http://steamcommunity.com/profiles/76561198165225182

but it appears when creating instances with different steam url's
in each loop i create an instance with a different steam url and each time i call me.recently_played on it to gather data and sometimes in maybe ~3000 cases i get this error.

**Comment by smiley** [comment]
Oh, okay. Can you give me the list of those IDs? Or where you're getting them from?

**Comment by lyux94** [comment]
i just random these, i have the above given id as start id and then just take the id - random.rand(50)

**Comment by smiley** [comment]
Started looking into this and found another bug with private profiles, but while the test was running the web API went down. But anyway, can you change your loop to catch the `AttributeError` and save the ID you were trying to query, then post it here? Maybe it's got something to do with specific user settings.

**Comment by lyux94** [comment]
This is what i got just now with the id: 76561198165229687

    Traceback (most recent call last):
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\decorators.py", line 67, in   __get__
    value, last_update = inst._cache[self.__name__]
    AttributeError: 'SteamUser' object has no attribute '_cache'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "C:\Users\Dirk\Desktop\Derp\test.py", line 75, in <module>
      process()
    File "C:\Users\Dirk\Desktop\Derpsetup\test.py", line 52, in process
     checker.checkforcs()
    File "C:\Users\Dirk\Desktop\Derpsetup\checker.py", line 10, in checkforcs
      games = test.me.recently_played
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\decorators.py", line 71, in __get__
      value = self.fget(inst)
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\user.py", line 372, in recently_played
      return self._convert_games_list(response.games, self._id)
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\user.py", line 149, in _convert_games_list
    game_obj = SteamApp(game.appid, game.name, associated_userid)
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\core.py", line 506, in __getattribute__
    attr=item))
    AttributeError: 'APIResponse' has no attribute 'name'
    Traceback (most recent call last):
     File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\decorators.py", line 67, in __get__
    value, last_update = inst._cache[self.__name__]
    AttributeError: 'SteamUser' object has no attribute '_cache'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "C:\Users\Dirk\Desktop\Derpsetup\test.py", line 75, in <module>
      process()
    File "C:\Users\Dirk\Desktop\Derpsetup\test.py", line 52, in process
      checker.checkforcs()
    File "C:\Users\Dirk\Desktop\Derpsetup\checker.py", line 10, in checkforcs
     games = test.me.recently_played
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\decorators.py", line 71, in __get__
    value = self.fget(inst)
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\user.py", line 372, in recently_played
    return self._convert_games_list(response.games, self._id)
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\user.py", line 149, in _convert_games_list
    game_obj = SteamApp(game.appid, game.name, associated_userid)
    File "C:\Python34\lib\site-packages\steamapi-0.1-py3.4.egg\steamapi\core.py", line 506, in __getattribute__
    attr=item))
AttributeError: 'APIResponse' has no attribute 'name'

**Comment by smiley** [comment]
Ah, looks like the API is returning just an app ID and nothing more:

```json
{
	"response": {
		"total_count": 2,
		"games": [
			{
				"appid": 372000,
				"playtime_2weeks": 2815,
				"playtime_forever": 20839
			},
			{
				"appid": 730,
				"name": "Counter-Strike: Global Offensive",
				"playtime_2weeks": 168,
				"playtime_forever": 1081,
				"img_icon_url": "69f7ebe2735c366c65c0b33dae00e12dc40edbe4",
				"img_logo_url": "d0595ff02f5c79fd19b06f4d6165c3fda2372820"
			}
		]
		
	}
}
```

The attached app ID is unknown, [even to SteamDB](https://steamdb.info/app/372000/subs/), but it looks like an unpublished game in development. I'll add support for this now.
