### ISSUE TITLE
issue au launching bot 

### ISSUE THREAD

**Issue by wedzyou** [smiley/steamapi#42]
hi when i launch the file storehouse.py i got this error (i'm on unbuntu)
Traceback (most recent call last):
  File "storehouse.py", line 47, in <module>
    main()
  File "storehouse.py", line 21, in main
    client.login(username, password, steamguard_path)
  File "/home/thomas/.local/lib/python3.5/site-packages/steampy/client.py", line 76, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "/home/thomas/.local/lib/python3.5/site-packages/steampy/login.py", line 24, in login
    self._check_for_captcha(login_response)
  File "/home/thomas/.local/lib/python3.5/site-packages/steampy/login.py", line 67, in _check_for_captcha
    raise CaptchaRequired('Captcha required')
steampy.login.CaptchaRequired: Captcha required

**Comment by smiley** [comment]
You got the wrong project, there's no file named `storehouse.py`. (I think you meant to go to [`bukson/steampy`](https://github.com/bukson/steampy))
